#ifndef _REQUEST_TYPE_H_
#define _REQUEST_TYPE_H_

enum RequestType {

   REQUEST_TYPE_ADD_POINT,
   REQUEST_TYPE_UPDATE_POINT,
   REQUEST_TYPE_POINT_DATA,
   REQUEST_TYPE_POLYGON_DATA

};

#endif // _REQUEST_TYPE_H_
