#ifndef _REQUEST_TYPE_H_
#define _REQUEST_TYPE_H_

enum RequestType {

   REQUEST_TYPE_ADD_POINT,
   REQUEST_TYPE_UPDATE_POINT,
   REQUEST_TYPE_POINT_DATA,
   REQUEST_TYPE_POLYGON_DATA,
   REQUEST_TYPE_CLUSTER_REPLACE,
   REQUEST_TYPE_SHADOW_UPDATE,
   REQUEST_TYPE_SNAPSHOT,
   REQUEST_TYPE_SLOWDOWN,
   REQUEST_TYPE_SPEED_WARNING
};

#endif // _REQUEST_TYPE_H_
